name: flutter_epam_kazakh
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3
  shared_preferences: ^2.2.3
  # flutter_localizations:
  # sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  logging: ^1.2.0
  json_annotation: ^4.8.1
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  path: ^1.8.3
  meta: ^1.10.0
  # intl: ^0.18.1
  go_router: ^13.2.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  provider: ^6.1.2
  firebase_core: ^2.27.0
  freezed: ^2.5.2
  flutter_sound: ^9.4.6
  permission_handler: ^11.3.1
  just_audio: ^0.9.37
  http: ^1.2.0
  http_parser: ^4.0.2
  font_awesome_flutter: ^10.7.0
  neumorphic_button: ^0.0.1+2
  lottie: ^3.1.0
  record: ^5.0.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  analyzer: ^5.12.0
  flutter_lints: ^2.0.0
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/avatars/
    - assets/translations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
          weight: 600
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 100
    - family: Manrope_bold
      fonts:
        - asset: assets/app_font/Manrope-Bold.ttf
    - family: Manrope_regular
      fonts:
        - asset: assets/app_font/Manrope-Regular.ttf
    - family: Manrope_medium
      fonts:
        - asset: assets/app_font/Manrope-Medium.ttf
    - family: Manrope_light
      fonts:
        - asset: assets/app_font/Manrope-Light.ttf
    - family: Manrope_semibold
      fonts:
        - asset: assets/app_font/Manrope-SemiBold.ttf
