name: flutter_epam_kazakh
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3
  shared_preferences: ^2.2.3
  # flutter_localizations:
  # sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  logging: ^1.2.0
  json_annotation: ^4.8.1
  # location: ^5.0.3
  # google_maps_flutter: ^2.5.3
  path: ^1.8.3
  meta: ^1.10.0
  # intl: ^0.18.1
  go_router: ^13.2.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  analyzer: ^5.12.0
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  # generate: true
  uses-material-design: true
