// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUa5nZXJk9u3Q42AXXqvsDK4DbTv3yq70',
    appId: '1:310451798799:web:13efe9e09287ea367df47a',
    messagingSenderId: '310451798799',
    projectId: 'epam-hacknu',
    authDomain: 'epam-hacknu.firebaseapp.com',
    storageBucket: 'epam-hacknu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw08p-YusHyFm-N043K3YvGqoEnecypNo',
    appId: '1:310451798799:android:5576f42b2f9113a47df47a',
    messagingSenderId: '310451798799',
    projectId: 'epam-hacknu',
    storageBucket: 'epam-hacknu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeQbV3SaVGweb-ReiLLkhGQ83Gkn5DKy0',
    appId: '1:310451798799:ios:fa1492275a4ae9967df47a',
    messagingSenderId: '310451798799',
    projectId: 'epam-hacknu',
    storageBucket: 'epam-hacknu.appspot.com',
    iosBundleId: 'com.example.flutterEpamKazakh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeQbV3SaVGweb-ReiLLkhGQ83Gkn5DKy0',
    appId: '1:310451798799:ios:97f62c4f40bde5b07df47a',
    messagingSenderId: '310451798799',
    projectId: 'epam-hacknu',
    storageBucket: 'epam-hacknu.appspot.com',
    iosBundleId: 'com.example.flutterEpamKazakh.RunnerTests',
  );
}
